### ISSUE TITLE
Problem with version 1.1.0

### ISSUE THREAD

**Issue by tkirshboim** [hexojs/hexo-generator-sitemap#15]
Hello,

I encountered a problem with the latest version of this module.
When I run the following commands:
```
$ hexo init blog
$ cd blog
$ npm install
$ npm install hexo-generator-sitemap --save
$ hexo server
```
The server fails to start with the following error message:
```
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: Cannot read property 'indexOf' of null
    at /basepath/blog/node_modules/hexo-generator-sitemap/lib/generator.js:25:60
    at Array.filter (native)
    at Hexo.module.exports (/basepath/blog/node_modules/hexo-generator-sitemap/lib/generator.js:24:6)
    at Hexo.tryCatcher (/basepath/blog/node_modules/bluebird/js/main/util.js:26:23)
    at Hexo.<anonymous> (/basepath/blog/node_modules/bluebird/js/main/method.js:15:34)
    at /basepath/blog/node_modules/hexo/lib/hexo/index.js:325:24
    at tryCatcher (/basepath/blog/node_modules/bluebird/js/main/util.js:26:23)
    at MappingPromiseArray._promiseFulfilled (/basepath/blog/node_modules/bluebird/js/main/map.js:56:38)
    at MappingPromiseArray.init (/basepath/blog/node_modules/bluebird/js/main/promise_array.js:92:18)
    at MappingPromiseArray.init (/basepath/blog/node_modules/bluebird/js/main/map.js:29:23)
    at Async._drainQueue (/basepath/blog/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/basepath/blog/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/basepath/blog/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

I managed to work around it by using version 1.0.0 instead of 1.1.0 by running
```
npm uninstall hexo-generator-sitemap
npm install hexo-generator-sitemap@1.0.0 --save
```

When I run ```hexo server``` with version 1.0.0 it works, so I'm guessing it's something with version 1.1.0

This is the output of `hexo -v`:
```
$ hexo -v
hexo: 3.1.1
os: Darwin 14.5.0 darwin x64
http_parser: 2.6.0
node: 5.5.0
v8: 4.6.85.31
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2e
```

**Comment by tkirshboim** [comment]
Works with version 1.1.0. Thanks for the quick response! :clap:
