### ISSUE TITLE
Zsh plug load failed 

### ISSUE THREAD

**Issue by Gowa2017** [hexojs/hexo-generator-sitemap#80]
/home/gowa/hexo/node_modules/hexo-generator-sitemap/node_modules/micromatch/index.js:44
    let isMatch = picomatch(String(patterns[i]), { ...options, onResult }, true);
                                                   ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/gowa/hexo/node_modules/hexo-generator-sitemap/lib/generator.js:3:20)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (/home/gowa/hexo/node_modules/hexo/lib/hexo/index.js:227:21)
    at /home/gowa/hexo/node_modules/hexo-generator-sitemap/index.js:15:43
    at fs.readFile.then.script (/home/gowa/hexo/node_modules/hexo/lib/hexo/index.js:240:12)
    at tryCatcher (/home/gowa/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/gowa/hexo/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/gowa/hexo/node_modules/bluebird/js/release/promise.js:569:18)

Bash is ok

**Comment by stevenjoezhang** [comment]
Please check your environment variables and Node.js version
